export const ADD_ARTICLE = "ADD_ARTICLE";

export const preProducts = {
  SET_PREPRODDUCT: "SET_PREPRODUCT",
};

export const PRODUCTS_ACTIONS = {
  CLEAR_PRODUCTS: "CLEAR_PRODUCTS",
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  ADD_PRODUCT: "ADD_PRODUCT",
};

export const PRE_PRODUCTS_ACTIONS = {
  GET_PRE_PRODUCT_BY_URL: "GET_PRE_PRODUCT_BY_URL",
  GETTING_PREPRODUCT_IN_PROGRESS_START: "GETTING_PREPRODUCT_IN_PROGRESS_START",
  GETTING_PREPRODUCT_IN_PROGRESS_END: "GETTING_PREPRODUCT_IN_PROGRESS_END",
  CREATE_PRODUCT_IN_PROGRESS_START: "CREATE_PRODUCT_IN_PROGRESS_START",
  CREATE_PRODUCT_IN_PROGRESS_END: "CREATE_PRODUCT_IN_PROGRESS_END",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_IN_PROGRESS_START",
  CREATE_PRODUCT_FAIL: "CREATE_PRODUCT_IN_PROGRESS_START",
};
